[package]
name = "lolz"
version = "0.1.0"
authors = ["Silas Pockendahl <silch20@student.sdu.dk>"]
edition = "2018"

[dependencies]
# clap = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
chrono = {version="*",features=["serde"]}